version: "3.8"

services:
  device:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./volume/ssh:/root/.ssh
      - ./volume/ssh-scripts:/workspace/ssh-scripts
      - ./volume/terraform:/workspace/volume/terraform
    working_dir: /workspace
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
